//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FtpActivities.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UFtpLibray.Activities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity timeout exceeded..
        /// </summary>
        internal static string ActivityTimeout {
            get {
                return ResourceManager.GetString("ActivityTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExistingUiBrowser.
        /// </summary>
        internal static string BrowserPropertyName {
            get {
                return ResourceManager.GetString("BrowserPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This activity has been deprecated. Use Set Clipping Region instead.
        /// </summary>
        internal static string DeprecatedExpandClipDeprecatedExpandClippingRegion {
            get {
                return ResourceManager.GetString("DeprecatedExpandClipDeprecatedExpandClippingRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This activity has been deprecated. Use Set Clipping Region instead..
        /// </summary>
        internal static string DeprecatedExpandClippingRegion {
            get {
                return ResourceManager.GetString("DeprecatedExpandClippingRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This activity has been deprecated. Use Get Attribute Value instead..
        /// </summary>
        internal static string DeprecatedGetAttribute {
            get {
                return ResourceManager.GetString("DeprecatedGetAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OffsetDirection is deprecated. Re-calculate the offsets based on Position property and reload the workflow..
        /// </summary>
        internal static string DeprecateOffsetDirection {
            get {
                return ResourceManager.GetString("DeprecateOffsetDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExistingUiElement.
        /// </summary>
        internal static string ElementPropertyName {
            get {
                return ResourceManager.GetString("ElementPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [d(ctrl)]a[u(ctrl)][k(del)].
        /// </summary>
        internal static string EmptyFieldSequence {
            get {
                return ResourceManager.GetString("EmptyFieldSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1500.
        /// </summary>
        internal static string HighlightSleepTime {
            get {
                return ResourceManager.GetString("HighlightSleepTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function (e) {
        ///    // For frame/iframe scenario we need to get the parent document of parameter dummyElem.
        ///    // In Chrome/Firefox, the document refers to top document; for IE it should be already set to iframe/frame document.
        ///    var htmlDoc = document;
        ///    if (e &amp;&amp; e.ownerDocument) {
        ///        htmlDoc = e.ownerDocument;
        ///    }
        ///    if (!htmlDoc.body.contains(e)) return &apos;false&apos;;
        ///    if (window.getComputedStyle(e).visibility === &apos;hidden&apos;) return &apos;false&apos;;
        ///    do {
        ///        if (window.getComputedStyle(e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IsVisibleFromStyle {
            get {
                return ResourceManager.GetString("IsVisibleFromStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running this activity requires one of the following permissions: {0}. 
        ///Please contact support@deskover.com.
        /// </summary>
        internal static string MultipleMissingPermissions {
            get {
                return ResourceManager.GetString("MultipleMissingPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running this activity requires the {0} permission. 
        ///Please contact support@deskover.com].
        /// </summary>
        internal static string OneMissingPermission {
            get {
                return ResourceManager.GetString("OneMissingPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selector is not relative to the Existing UiElement.
        /// </summary>
        internal static string PartialSelectorException {
            get {
                return ResourceManager.GetString("PartialSelectorException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not licensed to run UiPath activities. Please contact support@deskover.com.
        /// </summary>
        internal static string RegistrationError {
            get {
                return ResourceManager.GetString("RegistrationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax error in the selector..
        /// </summary>
        internal static string SyntaxError {
            get {
                return ResourceManager.GetString("SyntaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text was not found.
        /// </summary>
        internal static string TextNotFoundException {
            get {
                return ResourceManager.GetString("TextNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial has expired..
        /// </summary>
        internal static string TrialExpired {
            get {
                return ResourceManager.GetString("TrialExpired", resourceCulture);
            }
        }
    }
}
